# Generated by Django 5.1.2 on 2024-12-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_conteudo_descricao_3_conteudo_descricao_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='descricao_4',
            field=models.TextField(blank=True, help_text='Descrição mais longa', max_length=200, null=True),
        ),
    ]
